# Generated by Django 3.1.4 on 2020-12-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='covers/%Y/%m/%d'),
        ),
    ]
